[project]
name = "audio-anonym"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "elevenlabs>=2.24.0",
    "fastapi>=0.121.3",
    "numpy>=2.3.5",
    "python-dotenv>=1.2.1",
]
